version: "3"
services:
  anomalous-metrics:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      # - read_only: true
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
